name: Setup Environment
inputs:
  SECRET_GITHUB_TOKEN:
    required: true
    description: 'Github Secret Token'
  CACHIX_TOKEN:
    required: true
    description: 'Cachix Secret Token'
runs:
  using: "composite"
  steps:

    - name: Installing Nix
      uses: cachix/install-nix-action@v23
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        github_access_token: ${{ inputs.SECRET_GITHUB_TOKEN }}
        extra_nix_config: |
          substituters = https://tweag-nickel.cachix.org https://cache.nixos.org/
          trusted-public-keys = tweag-nickel.cachix.org-1:GIthuiK4LRgnW64ALYEoioVUQBWs0jexyoYVeLDBwRA= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - name: Configure Cachix
      uses: cachix/cachix-action@v12
      with:
        name: organist
        authToken: ${{ inputs.CACHIX_TOKEN }}
